### ISSUE TITLE
Add proper licence

### ISSUE THREAD

**Issue by selrond** [streamich/use-media#150]
Please consider adding a licence to your project:

> ...without a license, the default copyright laws apply, meaning that **you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work**.
— [Licensing a repository - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license "Licensing a repository - GitHub Docs")

(emphasis is mine)

Other than that, it's a common requirement when including it as a dependency for a commercial product. 

https://choosealicense.com/

**Comment by pavelkornev** [comment]
whitesource scanner also complains about this unlicensed dependency... and therefore we need to drop it from our project, but library is useful! :\

**Comment by PhilippeVienne** [comment]
Note that if you look to package.json, you see License applicable to this package is currently the [Unlicense](https://unlicense.org/)

**Comment by streamich** [comment]
The license is Unlicense, i.e. it is public domain. https://github.com/streamich/use-media/commit/109c98f6d91a1af654beddd4906d86a4850e2c58
