### ISSUE TITLE
Not working. React 18.2.0

### ISSUE THREAD

**Issue by ex-tag** [streamich/use-media#202]
```shell
npm i --save use-media
```

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving:
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from use-media@1.4.0
npm ERR! node_modules/use-media
npm ERR!   use-media@"*" from the root project
```

**Comment by william-will-angi** [comment]
@streamich it looks like you added the react 17 & 18 peer dependencies, but didn't release a new version. Any chance you could release those changes once you have the time?

**Comment by rikkertkoppes** [comment]
I'd like to bring this to your attention. Please release a new version to fix this

**Comment by nnmax** [comment]
@streamich release please

**Comment by mcasassa-ext** [comment]
@streamich 4 years since a update, are there alternative packages anyone can provide to use with node 18?

**Comment by streamich** [comment]
Peer dependencies are `*` now.
