### ISSUE TITLE
useLayoutEffect

### ISSUE THREAD

**Issue by BrianMitchL** [streamich/use-media#7]
I am using this hook for determining if a user is on a mobile or desktop device, and to conditionally expand or collapse a menu. I am using a `useLayoutEffect` hook for setting state based on the `useMedia` hook, but this hook uses `useEffect`, which causes another render and for the UI to flash into place on the second render, immediately after. I've tried switching the defaultState, but that just moves the problem to the other match case.

How do you feel about a second export that uses `useLayoutEffect` so consumers can choose which type of effect they would like to use?

**Comment by BrianMitchL** [comment]
I'm more than happy to submit a PR with a `useMediaLayout` (or something similar) named export that uses `useLayoutEffect` if that seems okay.

**Comment by streamich** [comment]
Does it make sense to only have `useLayoutEffect`? Or are there cases where `useEffect` if preferable for this hook?

**Comment by streamich** [comment]
> ... if that seems okay.

That would be great, I'm just thinking if we can just replace `useEffect` with `useLayoutEffect`.

**Comment by BrianMitchL** [comment]
There are probably cases for both. For my uses, I feel like I would only use a layout effect, but there are a ton of media queries, I doubt all need to be run synchronously.

**Comment by streamich** [comment]
OK, then we can create `useMediaLayout`.

**Comment by streamich** [comment]
Maybe something like this:

```js
const useMedia = createUseMedia(useEffect);
const useMediaLayout = createUseMedia(useLayoutEffect);
```

**Comment by BrianMitchL** [comment]
Oh yeah, nice! I'll give that a go and submit a PR.

**Comment by streamich** [comment]
Thanks for adding this, it should be in `1.3.0` now.
